image:
  repository: sumon124816/openstack
  tag: ccm
  pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits: {}

cloudConfig:
  loadBalancer:
    creationPollInterval: 5
    creationPollTimeout: 60
  instancesV2:
    enabled: true
    zoneAndRegionEnabled: false

rpcServerAddr: "10.2.3.250:9000"
rpcKeepAlive: 30
rpcRetryMax: 3
networkID: "6fdf82fd-659c-435b-9452-2677689229b5"
subnetID: "a6b34727-fd97-4085-ba63-7784195218a4"
fipNetworkID: "013234de-62ee-48ce-9c2b-cb0849b335a4"
ipType: "external" # internal, external, both
tenantID: "b4e90e6f0982470ba5472483e82c7db8"

serviceAccount:
  create: true
  name: cloud-controller-manager

role:
  apiGroups:
    - kubevirt.io
  resources:
    - virtualmachines
    - virtualmachineinstances
  verbs:
    - get
    - watch
    - list
    - update
  nonResourceURLs: []

clusterName: "ccm"

# when true, disables node and route controllers, keeping only loadbalancer (service) + EPS controllers
onlyServiceController: false