{{- if .Values.kubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-kubeconfig
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kubevirt-cloud-controller-manager.labels" . | nindent 4 }}
type: Opaque
data:
  value: {{ .Values.kubeconfig | b64enc }}
{{- end }}