{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubevirt-cloud-controller-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevirt-cloud-controller-manager.labels" . | nindent 4 }}
{{- end }}